big rewrite of json() and refactor of errors/warnings internal structure

diff --git a/files/etc/init.d/adblock-fast b/files/etc/init.d/adblock-fast
--- a/files/etc/init.d/adblock-fast
+++ b/files/etc/init.d/adblock-fast
@@ -1,6 +1,6 @@
 #!/bin/sh /etc/rc.common
 # Copyright 2023-2025 MOSSDeF, Stan Grishin (stangri@melmac.ca)
-# shellcheck disable=SC2015,SC3043
+# shellcheck disable=SC2015,SC3023,SC3043
 
 # shellcheck disable=SC2034
 START=94
@@ -26,7 +26,7 @@ fi
 
 readonly packageName='adblock-fast'
 readonly PKG_VERSION='dev-test'
-readonly packageCompat='6'
+readonly packageCompat='7'
 readonly serviceName="$packageName $PKG_VERSION"
 readonly packageMemoryThreshold='33554432'
 readonly packageConfigFile="/etc/config/${packageName}"
@@ -88,8 +88,8 @@ readonly B_TMP="/var/${packageName}.b.tmp"
 readonly SED_TMP="/var/${packageName}.sed.tmp"
 readonly uciConfigFile="/etc/config/${packageName}"
 readonly runningConfigFile="/dev/shm/${packageName}"
-readonly runningErrorFile="/dev/shm/${packageName}.error"
-readonly runningStatusFile="/dev/shm/${packageName}.status"
+readonly runningStatusFile="/dev/shm/${packageName}.status.json"
+readonly runningStatusFileLock="/var/lock/${packageName}.lock"
 readonly hostsFilter='/localhost/d;/^#/d;/^[^0-9]/d;s/^0\.0\.0\.0.//;s/^127\.0\.0\.1.//;s/[[:space:]]*#.*$//;s/[[:cntrl:]]$//;s/[[:space:]]//g;/[`~!@#\$%\^&\*()=+;:"'\'',<>?/\|[{}]/d;/]/d;/\./!d;/^$/d;/[^[:alnum:]_.-]/d;'
 readonly domainsFilter='/^#/d;s/[[:space:]]*#.*|[[:space:]]*$|[[:cntrl:]]$//g;/^[[:space:]]*$/d;/^[^[:alnum:]._-]|[`~!@#\$%\^&\*()=+;:"'"'"',<>?/\|{}]/d'
 readonly adBlockPlusFilter='/^#/d;/^!/d;s/[[:space:]]*#.*$//;s/^||//;s/\^$//;s/[[:space:]]*$//;s/[[:cntrl:]]$//;/[[:space:]]/d;/[`~!@#\$%\^&\*()=+;:"'\'',<>?/\|[{}]/d;/]/d;/\./!d;/^$/d;/[^[:alnum:]_.-]/d;'
@@ -265,9 +265,9 @@ adb_config_cache() {
 }
 count_blocked_domains() {
 	if [ -n "$outputBlockedCountFilter" ]; then
-		sed "$outputBlockedCountFilter" "$outputFile" | wc -l
+		[ -f "$outputFile" ] && sed "$outputBlockedCountFilter" "$outputFile" | wc -l || echo '0'
 	else
-		wc -l < "$outputFile"
+		[ -f "$outputFile" ] && wc -l < "$outputFile" || echo '0'
 	fi
 }
 debug() { local __i __j; for __i in "$@"; do eval "__j=\$$__i"; echo "${__i}: ${__j} "; done; }
@@ -384,8 +384,8 @@ is_newline_ending() { [ "$(tail -c1 "$1" | wc -l)" -ne '0' ]; }
 is_present() { command -v "$1" >/dev/null 2>&1; }
 is_running() {
 	local i j
-	i="$(json get 'status')"
-	j="$(ubus_get_data 'status')"
+	i="$(json get status)"
+	j="$(ubus_get_data status)"
 	if [ "$i" = 'statusStopped' ] || [ -z "${i}${j}" ]; then
 		return 1
 	else
@@ -413,6 +413,8 @@ nft() { "$nft" "$@" >/dev/null 2>&1; }
 output_dot() { output 1 "$_DOT_"; output 2 "$__DOT__"; }
 output_ok() { output 1 "$_OK_"; output 2 "$__OK__\n"; }
 output_okn() { output 1 "$_OK_\n"; output 2 "$__OK__\n"; }
+output_warn() { output 1 "$_WARN_"; output 2 "$__WARN__\n"; }
+output_warnn() { output 1 "$_WARN_\n"; output 2 "$__WARN__\n"; }
 output_fail() { output 1 "$_FAIL_"; output 2 "$__FAIL__\n"; }
 output_failn() { output 1 "$_FAIL_\n"; output 2 "$__FAIL__\n"; }
 output_error() { output "${_ERROR_} $*!\n"; }
@@ -438,53 +440,86 @@ uci_get_protocol() { uci_get 'network' "$1" 'proto'; }
 unbound_restart() { /etc/init.d/unbound restart >/dev/null 2>&1; }
 
 json() {
-# shellcheck disable=SC2034
-	local action="$1" param="$2" value="$3"
-	shift 3
-# shellcheck disable=SC2124
-	local extras="$@" line
-	local status message error warning stats
-	local ret i
-	if [ -s "$runningStatusFile" ]; then
-		json_load_file "$runningStatusFile" 2>/dev/null
-		json_select 'data' 2>/dev/null
-		for i in status message error warning stats; do
-			json_get_var "$i" "$i" 2>/dev/null
-		done
-	fi
-	case "$action" in
-		get)
-			printf "%b" "$(eval echo "\$$param")"
-			return
-		;;
-		add)
-			line="$(eval echo "\$$param")"
-			eval "$param"='${line:+$line }${value}${extras:+|$extras}'
-		;;
-		del)
-			case "$param" in
-				all)
-					unset status message error warning stats;;
-				*)
-					unset "$param";;
-			esac
-		;;
-		set)
-			eval "$param"='${value}${extras:+|$extras}'
-		;;
-	esac
-	json_init
-	json_add_object 'data'
-	json_add_string version "$PKG_VERSION"
-	json_add_string status "$status"
-	json_add_string message "$message"
-	json_add_string error "$error"
-	json_add_string warning "$warning"
-	json_add_string stats "$stats"
-	json_close_object
-	mkdir -p "${runningStatusFile%/*}"
-	json_dump > "$runningStatusFile"
-	sync
+	{
+		flock -x 207
+		local status message stats i
+		local action="$1" param="$2" value="$3"; shift 3; local info="$*";
+		[ "$param" = 'error' ] && param='errors'
+		[ "$param" = 'warning' ] && param='warnings'
+		{ json_load_file "$runningStatusFile" || json_init; } >/dev/null 2>&1
+		{ json_select 'data' || { json_add_object 'data'; json_close_object; json_select 'data'; }; } >/dev/null 2>&1
+		case "$action" in
+			'get')
+				case "$param" in
+					'errors'|'warnings')
+						json_select "$param" >/dev/null 2>&1
+						if [ -z "$value" ]; then
+							json_get_keys i
+						else
+							json_select "$value" >/dev/null 2>&1
+							case "${info:-code}" in
+								'code'|'info') json_get_var 'i' "$info" >/dev/null 2>&1;;
+							esac
+						fi
+						printf "%b" "$i"
+						return
+					;;
+					'status'|'message'|'stats'|*)
+						json_get_var 'i' "$param" >/dev/null 2>&1
+						printf "%b" "$i"
+						return
+					;;
+				esac
+			;;
+			'add')
+				case "$param" in
+					'errors'|'warnings')
+						{ json_select "$param" || json_add_array "$param"; } >/dev/null 2>&1
+						json_add_object ""
+						json_add_string 'code' "$value"
+						json_add_string 'info' "$info"
+						json_close_object
+						json_select ..
+					;;
+					*)
+						json_add_string "$param" "$value"
+					;;
+				esac
+			;;
+			'del')
+				case "$param" in
+					'all')
+						json_add_string status ''
+						json_add_string message ''
+						json_add_string stats ''
+						json_add_array errors
+						json_close_array
+						json_add_array warnings
+						json_close_array
+					;;
+					'errors'|'warnings')
+						json_add_array "$param"
+						json_close_array
+					;;
+					*)
+						json_add_string "$param" '';;
+				esac
+			;;
+			set)
+				case "$param" in
+					'status'|'message'|'stats')
+						json_add_string "$param" "$value"
+					;;
+				esac
+			;;
+		esac
+		json_add_string 'version' "$PKG_VERSION"
+		json_add_string 'packageCompat' "$packageCompat"
+		json_select ..
+		mkdir -p "${runningStatusFile%/*}"
+		json_dump > "$runningStatusFile"
+		sync
+	} 207>"$runningStatusFileLock"
 }
 
 get_local_filesize() {
@@ -822,7 +857,7 @@ load_environment() {
 	[ "$dns" = 'smartdns.nftset' ]    || rm -f "$smartdnsNftsetFile" "$smartdnsNftsetCache" "${compressed_cache_dir}/${smartdnsNftsetGzip}" "$smartdnsNftsetConfig"
 	[ "$dns" = 'unbound.adb_list' ]   || rm -f "$unboundFile" "$unboundCache" "${compressed_cache_dir}/${unboundGzip}"
 
-	for i in "$runningConfigFile" "$runningErrorFile" "$runningStatusFile" "$outputFile" "$outputCache" "$outputGzip" "$outputConfig"; do
+	for i in "$runningConfigFile" "$runningStatusFile" "$outputFile" "$outputCache" "$outputGzip" "$outputConfig"; do
 		[ -n "$i" ] || continue
 		if ! mkdir -p "${i%/*}"; then
 			if [ "$param" != 'quiet' ]; then
@@ -1353,7 +1388,7 @@ process_file_url() {
 	if is_https_url "$url" && [ -z "$isSSLSupported" ]; then
 		output 1 "$_FAIL_"
 		output 2 "[DL] $type $label $__FAIL__\n"
-		echo "errorNoSSLSupport|${1}" >> "$runningErrorFile"
+		json add error 'errorNoSSLSupport' "${name:-$url}"
 		return 0
 	fi
 	while [ -z "$R_TMP" ] || [ -e "$R_TMP" ]; do
@@ -1363,7 +1398,7 @@ process_file_url() {
 		[ ! -s "$R_TMP" ]; then
 		output 1 "$_FAIL_"
 		output 2 "[DL] $type $label $__FAIL__\n"
-		echo "errorDownloadingList|${url}" >> "$runningErrorFile"
+		json add error 'errorDownloadingList' "${name:-$url}"
 	else
 		append_newline "$R_TMP"
 		[ -n "$cfg" ] && new_size="$(get_local_filesize "$R_TMP")"
@@ -1384,7 +1419,7 @@ process_file_url() {
 			*)
 				output 1 "$_FAIL_"
 				output 2 "[DL] $type $label $__FAIL__\n"
-				echo "errorDetectingFileType|${url}" >> "$runningErrorFile"
+				json add error 'errorDetectingFileType' "${name:-$url}"
 				rm -f "$R_TMP"
 				return 0
 			;;
@@ -1395,7 +1430,7 @@ process_file_url() {
 		if [ ! -s "$R_TMP" ]; then
 			output 1 "$_FAIL_"
 			output 2 "[DL] $type $label ($format) $__FAIL__\n"
-			echo "errorParsingList|${url}" >> "$runningErrorFile"
+			json add error 'errorParsingList' "${name:-$url}"
 		else
 			append_newline "$R_TMP"
 			cat "${R_TMP}" >> "$D_TMP"
@@ -1422,14 +1457,7 @@ download_dnsmasq_file() {
 	fi
 	touch "$ALLOWED_TMP" "$A_TMP" "$B_TMP" "$SED_TMP"
 	output 1 'Downloading dnsmasq file '
-	rm -f "$runningErrorFile"
 	process_file_url '' "$dnsmasq_config_file_url" 'file'
-	if [ -s "$runningErrorFile" ]; then
-		while IFS= read -r line; do
-			json add error "$line"
-		done < "$runningErrorFile"
-		rm -f "$runningErrorFile"
-	fi
 	output 2 '[DNS] Moving dnsmasq file '
 	local i __firstFile
 	for i in $outputDnsmasqFileList; do
@@ -1502,7 +1530,6 @@ download_lists() {
 	fi
 	touch "$ALLOWED_TMP" "$A_TMP" "$B_TMP" "$SED_TMP"
 	output 1 'Downloading lists '
-	rm -f "$runningErrorFile"
 	config_load "$packageName"
 	config_foreach load_validate_file_url_section 'file_url' process_file_url_wrapper
 	wait
@@ -1511,13 +1538,6 @@ download_lists() {
 		if [ -n "$update_config_sizes" ] && uci_commit "$packageName"; then output_ok; else output_fail; fi
 	fi
 	output 1 '\n'
-
-	if [ -s "$runningErrorFile" ]; then
-		while IFS= read -r line; do
-			json add error "$line"
-		done < "$runningErrorFile"
-		rm -f "$runningErrorFile"
-	fi
 
 	if [ "$canary_domains_icloud" -ne '0' ]; then
 		canaryDomains="${canaryDomains:+$canaryDomains }${canaryDomainsiCloud}"
@@ -2149,18 +2169,18 @@ adb_sizes() {
 
 # shellcheck disable=SC2120
 adb_start() {
-	local action status error message stats p iface
+	local action status error message stats p iface k
 	local param="$1" validation_result="$3"
 
 	[ -n "$adbf_boot_flag" ] && return 0
 	load_environment "$validation_result" "$param" || return 1
 
-	status="$(json get 'status')"
-	error="$(json get 'error')"
-	message="$(json get 'message')"
-	stats="$(json get 'stats')"
-	action="$(adb_config_cache get 'trigger_service')"
-	fw4_restart_flag="$(adb_config_cache get 'trigger_fw4')"
+	status="$(json get status)"
+	error="$(json get error)"
+	message="$(json get message)"
+	stats="$(json get stats)"
+	action="$(adb_config_cache get trigger_service)"
+	fw4_restart_flag="$(adb_config_cache get trigger_fw4)"
 
 	if [ "$action" = 'on_boot' ] || [ "$param" = 'on_boot' ] || [ "$param" = 'on_pause' ]; then
 		if adb_file 'test_gzip' || adb_file 'test_cache'; then
@@ -2246,8 +2266,6 @@ adb_start() {
 		fi
 	fi
 
-	adb_config_cache 'create'
-
 	if [ "$action" = 'restart' ]; then
 		output 1 "Restarting $serviceName...\n"
 		output 2 "[START] Restarting $serviceName...\n"
@@ -2277,19 +2295,33 @@ adb_start() {
 		status_service 'on_start_failure'
 	fi
 
+	adb_config_cache 'create'
+
 	procd_open_instance 'main'
 	procd_set_param command /bin/true
 	procd_set_param stdout 1
 	procd_set_param stderr 1
 	procd_open_data
-	json_add_string 'status' "$(json get status)"
-	json_add_string 'errors' "$(json get error)"
-	json_add_string 'warnings' "$(json get warning)"
-	if adb_file 'test'; then
-		json_add_int 'entries' "$(count_blocked_domains)"
-	else
-		json_add_int 'entries' '0'
-	fi
+	json_add_string 'version' "$PKG_VERSION"
+	json_add_string	'status' "$(json get status)"
+	json_add_int		'packageCompat' "$packageCompat"
+	json_add_int		'entries' "$(count_blocked_domains)"
+	json_add_array 'errors'
+		for k in $(json get errors); do
+			json_add_object "$k"
+			json_add_string 'code' "$(json get error "$k" 'code')"
+			json_add_string 'info' "$(json get error "$k" 'info')"
+			json_close_object
+		done
+	json_close_array
+	json_add_array 'warnings'
+		for k in $(json get warnings); do
+			json_add_object "$k"
+			json_add_string 'code' "$(json get warning "$k" 'code')"
+			json_add_string 'info' "$(json get warning "$k" 'info')"
+			json_close_object
+		done
+	json_close_array
 	json_add_array firewall
 	if [ "$force_dns" -ne '0' ]; then
 # shellcheck disable=SC3060
@@ -2386,6 +2418,7 @@ adb_start() {
 adb_status() {
 	local param="$1"
 	local c status message error warning stats text
+	local code info
 	status="$(json get status)"
 	message="$(json get message)"
 	error="$(json get error)"
@@ -2402,16 +2435,16 @@ adb_status() {
 	[ "$param" != 'quiet' ] || return 0
 	if [ -n "$error" ]; then
 		for c in $error; do
-			local error_param="${c##*|}"
-			local error_code="${c%|*}"
-			output_error "$(get_text "$error_code" "$error_param")"
+			code="$(json get error "$c" 'code')"
+			info="$(json get error "$c" 'info')"
+			output_error "$(get_text "$code" "$info")"
 		done
 	fi
 	if [ -n "$warning" ]; then
 		for c in $warning; do
-			local warning_param="${c##*|}"
-			local warning_code="${c%|*}"
-			output_warning "$(get_text "$warning_code" "$warning_param")"
+			code="$(json get warning "$c" 'code')"
+			info="$(json get warning "$c" 'info')"
+			output_warning "$(get_text "$code" "$info")"
 		done
 	fi
 }
